### PR TITLE
Handle feeds that use relative paths for links

### LINKED ISSUE #94: [FR] Try to auto-fix feeds that present relative URLs
## What

One of my feeds presents link URLs as relative paths rather than absolute URLs:

```bash
$ curl -s https://lgug2z.com/articles/index.xml | head -n 12
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Articles on LGUG2Z</title>
    <link>/articles/</link>
    <description>Recent content in Articles on LGUG2Z</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Tue, 18 Mar 2025 20:39:30 -0700</lastBuildDate><atom:link href="/articles/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Educational Source Software</title>
      <link>/articles/educational-source-software/</link>
            ^^^^ relative link
```

I think it's technically a problem with the feed rather than a problem with fusion, but it would be nice if fusion attempted to fix it.

Currently, fusion just treats it as a URL relative to itself, which is 100% going to be wrong. For example, if I'm running fusion at fusion.example.com and I add the above feed, fusion would create a link that points to `https://fusion.example.com/articles/educational-source-software/`

## Why

It makes the user experience easier for feeds that are misconfigured.

## (Optional) How

I can take this on after I [refactor the feed fetching code](https://github.com/0x2E/fusion/pull/84#issuecomment-2727600380), as it should be pretty easy once the RSS parsing is isolated to its own module that we can unit test.

### PR DESCRIPTION
**Pull request by mtlynch**
Some feeds use relative paths for the link field (e.g., "/item1" rather than "https://example.com/item1").

fusion's current behavior is to preserve the relative paths, but then when the user tries to click a link on one of these feeds, it sends the user to a non-existent path within fusion.

This fixes the interpretation of relative path links so that we automatically convert them back to absolute path URLs based on the feed URL.

Fixes #94

### CODE REVIEW

File: service/pull/client/parse.go [hunk 1]
```diff
@@ -34,3 +38,26 @@ func ParseGoFeedItems(gfItems []*gofeed.Item) []*model.Item {
...
 	return items
 }
+
+func parseLink(feedURL string, linkURL string) string {
+	// If the link URL is not a relative path, treat it as a full URL.
+	if !strings.HasPrefix(linkURL, "/") {
+		return linkURL
+	}
+
+	baseURL, err := url.Parse(feedURL)
```
Comment (0x2E) [inline service/pull/client/parse.go:48]: How about using `url.ResolveReference` like https://go.dev/play/p/JXp0ZgtGUPX

Comment (mtlynch) [reply service/pull/client/parse.go:48]: Ah, I didn't know about that. Thanks!

Fixed in [8cb9715](https://github.com/0x2E/fusion/pull/116/commits/8cb971574cd7ce5cfd61cf323ebe48b0dfba612b)

**Comment by 0x2E** [comment]
Thanks!
